const piezas = [
    {
        id: 1,
        tipo: 'Taza y derivados',
        img: './imagenes carrousel/chopcervecero.jpg',
        nombre: 'Chop Cervecero',
        descripcion: 'chop de color marron, capacidad: 750 cm3',
        precio: 15000,
        
    },
    {
        id: 2,
        tipo: 'Taza y derivados',
        img: './imagenes carrousel/setmate.jpg',
        nombre: 'Set Matero',
        descripcion: 'Conjunto de mate color marmol y detalles en bronce, incluye yerbera, azucarera y mate',
        precio: 25000,
    },
    {
        id: 3,
        tipo: 'Taza y derivados',
        img: './imagenes carrousel/tazahongo.jpeg',
        nombre: 'Taza personalizada',
        descripcion: 'Taza de 250 cm3 con relieve de forma de hongos',
        precio: 10000,
    },
    {
        id: 4,
        tipo: 'Taza y derivados',
        img: './imagenes carrousel/TazaMamá.jpg',
        nombre: 'Taza y plato',
        descripcion: 'Taza de 250 cm3 incluye plato ideal para regalo a mamá',
        precio: 12000,
    },
    {
        id: 5,
        tipo: 'Taza y derivados',
        img: './imagenes carrousel/tazasFlores.jpg',
        nombre: 'Taza con dibujo',
        descripcion: 'Tazones de 500cm3 con dibujos de flores con relieve',
        precio: 12000,
    },

    {
        id: 6,
        tipo: 'Taza y derivados',
        img: './imagenes carrousel/tazaybandeja.jpg',
        nombre: 'Taza y bandeja',
        descripcion: 'Taza de 250cm3 acompañado con una bandeja rectangular con detalles de flores',
        precio: 15000,
    },
    {
        id: 7,
        tipo: 'Platos y derivados',
        img: './imagenes carrousel/bandejapaisaje.jpg',
        nombre: 'Bandeja',
        descripcion: 'Bandeja rectangular plana de 30cmx15cm con dibujo personalizado',
        precio: 8000,
    },
    {
        id: 8,
        tipo: 'Platos y derivados',
        img: './imagenes carrousel/Compotera.jpg',
        nombre: 'Set Compotera',
        descripcion: 'Set de compoteras con colores marinos con textura granulada',
        precio: 8000,
    },
    {
        id: 9,
        tipo: 'Platos y derivados',
        img: './imagenes carrousel/plato.jpg',
        nombre: 'Plato playo',
        descripcion: 'Plato de 30cm de diametro en color naturales personalizado',
        precio: 8000,
    },
    {
        id: 10,
        tipo: 'Platos y derivados',
        img: './imagenes carrousel/platopostre.png',
        nombre: 'Plato para postre',
        descripcion: 'Plato principal 40cm y plato para postre de 15cm color beige con negro',
        precio: 8000,
    },
    {
        id: 11,
        tipo: 'Platos y derivados',
        img: './imagenes carrousel/setboul.jpg',
        nombre: 'Set Bowl',
        descripcion: 'Conjuntos de 5 Bowls con efecto de salpicadura ',
        precio: 30000,
    },
    {
        id: 12,
        tipo: 'Platos y derivados',
        img: './imagenes carrousel/setbowls.jpg',
        nombre: 'Set Bowl',
        descripcion: 'Conjuntos de 6 Bowls formas irregulares con colores marinos ideal para picada',
        precio: 35000,
    },
    {
        id: 13,
        tipo: 'otros',
        img: './imagenes carrousel/tetera.jpg',
        nombre: 'Tetera',
        descripcion: 'Set de tetera + pocillo ideal para la hora del té',
        precio: 35000,
    },

];